services:
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "2888:80"  # 宿主机 2888 → 容器 80
    volumes:
      - ../../data/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ../../data/nginx/conf.d:/etc/nginx/conf.d
    networks:
      - app_net

networks:
  app_net:
    external: true