version: "3.8"
services:
  
  speedtest:
    restart: unless-stopped
    container_name: openspeedtest
    ports:
      - 4000:3000
      - 4001:3001
    image: openspeedtest/latest
    networks:
      - app_net

  jupyter:
    restart: unless-stopped
    image: jupyter/base-notebook
    container_name: jupyter
    ports:
      - 4002:8888
    env_file: ../../.env
    volumes:
      - ../../data/jupyter/notebooks:/home/jovyan/work
    environment:
      - NB_UID=1001
      - NB_GID=1001
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_PASSWORD=${JUPYTER_PASSWORD}
    networks:
      - app_net

  code-server:
    image: linuxserver/code-server:latest
    container_name: code-server
    env_file: ../../.env
    environment:
      - PUID=1001
      - PGID=1001
      - TZ=Asia/Shanghai
      - PASSWORD=hjj123
      - DEFAULT_WORKSPACE=/config/workspace
    volumes:
      - ../../data/code-server:/config
      - ../../data/code-server/workspace:/config/workspace
    ports:
      - "4003:8080"
    restart: unless-stopped

networks:
  app_net:
    external: true